# Generated by Django 5.0.3 on 2024-03-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orde_venta',
            fields=[
                ('id_orden_ven', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ven', models.DateField()),
                ('total_ven', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estado_ven', models.CharField(max_length=50)),
                ('id_usuario_ven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_orden',
            fields=[
                ('id_detalle_ven', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_ven', models.IntegerField()),
                ('precio_ven', models.DecimalField(decimal_places=2, max_digits=9)),
                ('subtotal_ven', models.DecimalField(decimal_places=2, max_digits=9)),
                ('id_producto_ven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('id_orden_ven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.orde_venta')),
            ],
        ),
    ]
