# Generated by Django 5.0.3 on 2024-03-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orde_venta',
            name='estado_ven',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='orde_venta',
            name='total_ven',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
