# Generated by Django 5.0.3 on 2024-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_alter_orde_venta_estado_ven_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orde_venta',
            name='estado_ven',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprovado'), ('R', 'Rechazado'), ('E', 'Entregado')], default='P', max_length=1),
        ),
    ]
