# Generated by Django 5.0.3 on 2024-03-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_alter_orde_venta_estado_ven'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_orden',
            old_name='cantidad_ven',
            new_name='cantidad_det',
        ),
        migrations.RenameField(
            model_name='detalle_orden',
            old_name='id_detalle_ven',
            new_name='id_detalle_det',
        ),
        migrations.RenameField(
            model_name='detalle_orden',
            old_name='id_orden_ven',
            new_name='id_orden_det',
        ),
        migrations.RenameField(
            model_name='detalle_orden',
            old_name='id_producto_ven',
            new_name='id_producto_det',
        ),
        migrations.RenameField(
            model_name='detalle_orden',
            old_name='precio_ven',
            new_name='precio_det',
        ),
        migrations.RenameField(
            model_name='detalle_orden',
            old_name='subtotal_ven',
            new_name='subtotal_det',
        ),
        migrations.RenameField(
            model_name='orde_venta',
            old_name='estado_ven',
            new_name='estado_ord',
        ),
        migrations.RenameField(
            model_name='orde_venta',
            old_name='fecha_ven',
            new_name='fecha_ord',
        ),
        migrations.RenameField(
            model_name='orde_venta',
            old_name='id_orden_ven',
            new_name='id_orden_ord',
        ),
        migrations.RenameField(
            model_name='orde_venta',
            old_name='id_usuario_ven',
            new_name='id_usuario_ord',
        ),
        migrations.RenameField(
            model_name='orde_venta',
            old_name='total_ven',
            new_name='total_ord',
        ),
    ]
