# Generated by Django 5.0.3 on 2024-05-01 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_alter_producto_categoria_pro'),
        ('Ventas', '0005_alter_orde_venta_id_usuario_ord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_orden',
            name='cantidad_entregada_det',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle_orden',
            name='id_orden_det',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ventas.orde_venta'),
        ),
        migrations.AlterField(
            model_name='detalle_orden',
            name='id_producto_det',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.producto'),
        ),
        migrations.AlterField(
            model_name='orde_venta',
            name='id_usuario_ord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
