# Generated by Django 5.0.3 on 2024-05-01 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0006_detalle_orden_cantidad_entregada_det_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orde_venta',
            name='id_usuario_ord',
            field=models.ForeignKey(db_column='id_usuario_ord', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
