# Generated by Django 5.0.3 on 2024-03-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id_tipoUsuario_tus', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tus', models.CharField(max_length=50)),
                ('descripcion_tus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario_usu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usu', models.CharField(max_length=50)),
                ('apellido_usu', models.CharField(max_length=50)),
                ('correo_usu', models.CharField(max_length=50)),
                ('contrasena_usu', models.CharField(max_length=50)),
                ('tipoUsuario_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tipousuario')),
            ],
        ),
    ]
