# Generated by Django 5.0.3 on 2024-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario_usu',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
