# Generated by Django 5.0.3 on 2024-04-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_usuarioextendido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioExtendido',
        ),
    ]
