# Generated by Django 5.0.3 on 2024-05-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_usuario_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
    ]
