# Generated by Django 5.0.3 on 2024-03-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_pro',
            field=models.IntegerField(max_length=9),
        ),
    ]
