# Generated by Django 5.0.3 on 2024-03-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_producto_precio_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_pro',
            field=models.IntegerField(),
        ),
    ]
